services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-conduit-db}
      POSTGRES_USER: ${DB_USERNAME:-job}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-protection}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME:-job} -d ${DB_DATABASE:-conduit-db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: conduit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
